# Generated by Django 6.0.3 on 2026-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('poste', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='joueurs/')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_adverse', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('score_us', models.IntegerField(blank=True, null=True)),
                ('score_adverse', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
